name: Build and Release PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    env:
      PDF_FILENAME: ${{ vars.PDF_FILENAME || format('{0}.pdf', github.event.repository.name) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Rename main.pdf to $PDF_FILENAME
        run: mv main.pdf "$PDF_FILENAME"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ${{ env.PDF_FILENAME }}

      - name: Get short commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-${{ env.SHORT_SHA }}
          name: Prerelease ${{ env.SHORT_SHA }}
          files: ${{ env.PDF_FILENAME }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
