name: Build PDF

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -  name: Github Action for LaTeX
         uses: xu-cheng/latex-action@v3
         with:
           root_file: main.tex
           compiler: xelatex
         
